altdoc: 0.6.0.9000
last_built: 2025-10-15T12:39:56+0000
urls:
  reference: https://eddelbuettel.github.io/rpushbullet/man
  article: https://eddelbuettel.github.io/rpushbullet/vignettes
pandoc: 3.1.3
pkgdown: 2.1.3
pkgdown_sha: ~
